spring.security.oauth2:
  resourceserver:
    jwt:
      jwk-set-uri: http://localhost:8081/realms/master/protocol/openid-connect/certs

spring:
  application:
    name: api-gateway
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
    gateway:
      default-filters:
        - TokenRelay=
      discovery:
        locator:
          enabled: true
      routes:
        - id: etudiants
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/etudiants/**
        - id: professeurs
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/professeurs/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web.cors.reactive: TRACE

server:
  port: 8099
