services:
  mysql-exam-jee:
    image: mysql:8.0
    container_name: container-exam-jee
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exam-jee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: passer123@
    ports:
      - 3307:3306
    volumes:
      - mysql_data_exam-jee:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-exam-jee:
    container_name: phpmyadmin-exam-jee
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8084:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-exam-jee
      PMA_USER: user
      PMA_PASSWORD: passer123@
    depends_on:
      - mysql-exam-jee
    restart: unless-stopped

volumes:
  mysql_data_exam-jee:
    driver: local